#+TITLE: Projects

* Things I want to buy
  | Item                                                                             | Note           | Price  |
  |----------------------------------------------------------------------------------+----------------+--------|
  | [[http://www.amazon.com/iOS-Programming-Ranch-Guides-ebook/dp/B004Z2NQJQ/ref%3Dpd_sim_kinc_1?ie%3DUTF8&m%3DAG56TWVU5XWC2][iOS Programming: The Big Nerd Ranch Guide]]                                        | Kindle version | $26.99 |
  | [[http://peepcode.com/products/cucumber][Use the Cucumber]]                                                                 | Peepcode       | $12.00 |
  | [[http://pragprog.com/book/hwcuc/the-cucumber-book][The Cucumber Book: Behaviour-Driven Development for Testers and Developers]]       | PragProg       | $20.00 |
  | [[http://pragprog.com/book/ktmack/mac-kung-fu][Mac Kung Fu: Over 300 Tips, Tricks, Hints, and Hacks for OS X Lion]]               | PragProg       | $22.00 |
  | [[http://pragprog.com/book/jcdeg/new-programmer-s-survival-manual][New Programmer's Survival Manual: Navigate Your Workplace, Cube Farm, or Startup]] |                | $19.00 |
  |                                                                                  |                |        |
* Keeping my life in plain text
  1) [[http://www.gnu.org/software/emacs/manual/html_node/emacs/index.html][Emacs Manual]]
  2) [[http://orgmode.org/][Org-Mode]]
     1) [[http://doc.norang.ca/org-mode.html][Org Mode - Organize Your Life In Plain Text!]]
     2) [[http://sachachua.com/blog/2007/12/a-day-in-a-life-with-org/][A day in a life with Org]]
     3) [[http://sachachua.com/blog/2007/12/clocking-time-with-emacs-org/][Clocking Time with Emacs Org]]
     4) [[http://sachachua.com/blog/2008/01/tagging-in-org-plus-bonus-code-for-timeclocks-and-tags/][Tagging in Org – plus bonus code for timeclocks and tags!]]
     5) [[http://members.optusnet.com.au/~charles57/GTD/org_dates/][Using dates and times in Emacs org-mode]]
     6) [[http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]
     7) [[http://orgmode.org/worg/org-tutorials/org-latex-export.html][LaTeX Export]]
     8) [[http://orgmode.org/worg/org-tutorials/org-google-sync.html][Google Calendar Synchronization]]
     9) [[http://orgmode.org/worg/org-tutorials/tracking-habits.html][Tracking Habits with Org-mode]]
     10) [[http://orgmode.org/worg/org-tutorials/org-beamer/tutorial.html][Writing Beamer presentations in org-mode]]
     11) [[http://orgmode.org/worg/org-tutorials/non-beamer-presentations.html][Writing Non-Beamer presentations in org-mode]]
     12) [[http://juanreyero.com/article/emacs/org-teams.html][Org-mode tricks for team management]]
     13) [[http://julien.danjou.info/org-contacts.html][Org-Contact]]
     14) [[gnus:Org-mode#0D7B51F9-9986-4C86-96B6-4341408085B3@gmail.com][This made me laugh]]
  3) [[http://www.latex-project.org/][Latex]]
     1) [[file:~/Dropbox/LaTex-Beginners-Guide-eBook19082011_1090426.pdf][LaTex Beginner's Guide]]
     2) [[http://www.cv-templates.info/2009/03/professional-cv-latex/][Writing Your Professional CV with LaTeX]]
  4) [[http://www.gnus.org/][Gnus]]
     1. [[http://gertm.blogspot.com/2009/06/my-little-gnus-and-gmail-howto.html][My little Gnus and Gmail howto]]
     2. [[http://www.efod.se/writings/gnus-and-courier][My experiences from setting up Gnus with nnimap and Courier IMAP]]
     3. [[http://www.reverttoconsole.com/blog/linux/gnus-emacs-and-gmail-getting-started/][Gnus, Emacs, and Gmail; Getting Started]]
  5) [[http://www.emacswiki.org/emacs/JabberEl][Emacs-Jabber]]
     1. [[https://sourceforge.net/projects/emacs-jabber/files/emacs-jabber%2520beta%2520versions/0.8.90/][Emacs-Jabber with xml namespace fix for gtalk]]
     2. [[http://emacs-jabber.sourceforge.net/manual-0.8.0/][Emacs-Jabber manual]]
  6) [[http://philjackson.github.com/magit/][Magit]]
     1) [[http://vimeo.com/2871241][Meet Magit]]
  7) Behaviour-Driven Development
     1) [[http://search.cpan.org/~sargie/Test-BDD-Cucumber-0.01/][Test::BDD::Cucumber]]
     2) [[http://code.google.com/p/uispec/][UISpec]]
     3) [[http://www.kiwi-lib.info/][Kiwi]]
  8) [[http://vimeo.com/14742598][Emacs-Calc]]
     1. [[http://www.emacswiki.org/emacs/AdvancedDeskCalculator][Advanced Desk Calculator]]
     2. [[http://www.xemacs.org/Documentation/packages/html/calc.html][Calc manual]]
     3. [[http://nullprogram.com/blog/2009/06/23/][The Emacs Calculator]]
  9) [[http://ledger-cli.org/][Ledger]]
     1) [[http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-ledger.html][Using Ledger for Accounting in Org-mode with Babel]]
     2) [[https://github.com/jwiegley/ledger/tree/next/lisp][Emacs interface to ledger]]
     3) [[http://bugsplat.info/2010-05-23-keeping-finances-with-ledger.html][Program your Finances: Command-line Accounting]]
     4) [[http://bugsplat.info/2011-07-09-program-your-finances-reporting-for-fun-and-profit.html][Program your Finances: Reporting for Fun and Profit]]
     5) [[http://bugsplat.info/2011-08-04-program-your-finances-vacation-tracking.html][Program Your Finances: Vacation Tracking]]
* Movies to watch
  1) [[Http://peepcode.com/products/cucumber][Use The Cucumber]]
* Starting a business
  1) Work on [[file:Elections.org][Elections Web Service]]
  2) Read [[http://www.entrepreneur.com/management/leadership/businessstrategies/article65230.html][How to Write Your Mission Statement]]
  3) Read [[http://www.freshbooks.com/blog/2011/08/16/becoming-a-business-owner-series-part-1-staying-balanced-while-busy/][Becoming a Business Owner Series Part 1: Staying Balanced While Busy]]
     1) Why are you in business?
     2) Who are your customers?
     3) What image of your business do you want to convey?
     4) What level of service do you provide?
     5) What roles do you and your employees play?
     6) What kind of relationships will you maintain with suppliers?
     7) How do you differ from your competitors?
     8) How will you use technology, processes, and services to reach your goals?
     9) What underlying philosophies or values guided your responses to the previous questions?
  4) Everyone in the business should have a WIKI page for there notes
     1) or a linkable WIKI that is composed of local WIKIs
        
